type = "webpack"
workers_dev = false
compatibility_date = "2024-12-31"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "slateboxjs-prod"
route = "assets.slatebox.com/*"